### ISSUE TITLE
Location of .config file(s) ?

### ISSUE THREAD

**Issue by martinboers** [PLCnext/vscode-plcnext-example#1]
Are there any .config files required to run this code in the PLC - e.g. .acf.config, and/or .plm.config? If so - are these included with the project? I couldn't find them in the repo (but I might just have not looked hard enough ...)

**Comment by bjoernsauer** [comment]
Hi Martin just look in the README.md file in the repository. The chapter _PLCnext Engineer Library_ explains how to generate a library that can be included into your PLCnext Engineer project. If you do so you wount need to write a acf or plm configuration file by your own. Because the C++ component library will be deployed on the target with the download of the PLCnext Engineer project.
